### ISSUE TITLE
@Restrict(@Group("my_group") or @SubjectNotPresent)

### ISSUE THREAD

**Issue by 8-bitLincoln** [schaloner/deadbolt-2-java#28]
Hi, there

I need something like @Restrict(@Group("my_group") or @SubjectNotPresent)
Can I combine these two annotations?

**Comment by schaloner** [comment]
If you're using Deadbolt 2.5, there's a feature called composite constraints.  This lets you combine restrictions, but by using a specific `@Composite` annotation.  Composite constraints can be arbitrarily complex, and it would be a nightmare to manage them as annotations (not least because they wouldn't be reusable).

Take a look at https://deadbolt-java.readme.io/docs/composite-constraints for details.
