### ISSUE TITLE
@Inherited is not respected

### ISSUE THREAD

**Issue by eximius313** [schaloner/deadbolt-2-java#86]
If I annotate my Controller as `@Restrict(@Group("MY_ROLE"))` - everything works, but if I annotate it as `@MyRoleOnly` where:
```
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE})
@Documented
@Inherited
@Restrict(@Group("MY_ROLE"))
public @interface MyRoleOnly {
}
```
it is ignored, despite the fact `@Restrict` is annotated by `@Inherited`

**Comment by mkurz** [comment]
I will check that next week

**Comment by mkurz** [comment]
@eximius313 I think your expectation that `@MyRoleOnly` should run/call `@Restrict(@Group("MY_ROLE"))` is wrong. That is not how `@Inherited` works. Please have a look at how `@Inherited` is supposted to work: https://stackoverflow.com/a/23973331/810109
As I understand it, it just means that any class extending a class which is annotated with `@MyRoleOnly` is automatically also annotated with `@MyRoleOnly`, but nothing more.

I am closing this since I think the behaviour is correct.
Please re-open if you think I am wrong.

**Comment by eximius313** [comment]
@mkurz could we then make it feature request, to be consistent with [Play Action Composition](https://www.playframework.com/documentation/2.6.x/JavaActionsComposition#Defining-custom-action-annotations)?

**Comment by mkurz** [comment]
Hmm... I think what you are looking for is https://deadbolt-java.readme.io/docs/composite-constraints?
Action composition is a different topic I think - you can now already create your own action annotation and call (a) desired deadbolt action. You could even use the Composite constraints feature and wrap the example from the docs e.g. `@Composite("curatorOrSubjectNotPresent")` in your own annotation.

**Comment by eximius313** [comment]
I don't want to have CompositeConstraint nor Action composition. I showed it as an example.
What I want is to have "Domain type" for constraint in the form of annotation (like it is resolved in action composition for example)

**Comment by mkurz** [comment]
@eximius313 I understand, however in the end `@MyRoleOnly` must be a Play action, otherwise Play doesn't pick up the annotation to run it. It has to be part of the action composition chain. That is a Play thing, not a deadbolt thing. How should Play know that `@MyRoleOnly` annotation on an action method is a constraint? How should Play know what to do with `@MyRoleOnly`? The whole deadbolt constraint annotation are just Play actions. That's just how it works. There is no way around - you would have to write your own `MyRoleOnly` action like like described [here](https://www.playframework.com/documentation/2.6.x/JavaActionsComposition#Defining-custom-action-annotations).
If an annotation does not have `@With(...)` defined Play does nothing with it, it's just useless. It doesn't matter if you put Inherited or something else on it, we just can't magically start to run the annotation.
```java
@With(SomeAction.class) <- This is what Play calls, that's just how it works
//...
public @interface MyRoleOnly { ... }
```

Do you understand what I want to say?

**Comment by mkurz** [comment]
OK, maybe it is possible... Let me think more...:

```java
@With(SomeSpecialDeadBoltAction.class) // -> This would have to check @MyRoleOnly if there is an @Restrict of some other constraint on it and run it...
@Restrict(@Group("MY_ROLE"))
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE})
@Documented
public @interface MyRoleOnly {
}
```

Maybe this is possible... I am not sure yet.
