### ISSUE TITLE
@Dynamic interferes with Config.load

### ISSUE THREAD

**Issue by eximius313** [schaloner/deadbolt-2-java#94]
When I use `ConfigFactory.load();` from controller not annotated with `@Dynamic` - I obtain fully loaded config with variables from `application.conf`
When I annotate method with `@Dynamic` only windows environmental variables are loaded.
`@Restrict` works fine. Deadbolt version: `2.6.4`, Play version: `2.6.15`

To reproduce just do:
```
@Dynamic(value = DynamicHandler.MY_HANDLER_KEY) // test with/without it
public CompletionStage<Result> test(final String something) {
    System.out.println(ConfigFactory.load());
    return CompletableFuture.completedFuture(ok());
}
```

**Comment by mkurz** [comment]
I will have a look at this as soon as I find time.

**Comment by eximius313** [comment]
@mkurz without it, I can not secure dynamic resources :(

**Comment by mkurz** [comment]
@eximius313 I will have a look coming week if I find time :wink:

**Comment by eximius313** [comment]
@mkurz were you able reproduce the problem?

**Comment by mkurz** [comment]
I doubt this has something to do with deadbolt, not even with Play. You make wrong assumptions about what `ConfigFactory.load()` does and how it works. Since you don't pass a classloader to `load()` I don't think you can rely on what it actually loads (specially in Play dev mode where different classloaders are involved).

You should inject the configuration:

```java
import com.typesafe.config.Config;

public class MyController extends Controller {

	private final Config config;
	
	@Inject
	public MyController(final Config config) {
		this.config = config;
	}

	@Dynamic(value = DynamicHandler.MY_HANDLER_KEY)
	public CompletionStage<Result> test(final String something) {
		// use this.config here
		return CompletableFuture.completedFuture(ok());
	}
}
```

**Comment by eximius313** [comment]
well, javadoc of `ConfigFactory.load()` says: `Loads a default configuration` which is exactly what I want.
Indeed injecting the config works, but the question is: "Why the problem occurs only with `@Dynamic`"?

**Comment by mkurz** [comment]
Reading the javadoc [here](https://github.com/lightbend/config/blob/v1.3.3/config/src/main/java/com/typesafe/config/ConfigFactory.java#L220-L226):
> Loads a default configuration, equivalent to load(defaultApplication()) **in most cases**.
> This configuration should be used **by libraries and frameworks** unless an application provides a different one.

So this method should be used **by libraries and frameworks**, not by applications itself (but this is what you tried). Also "**in most cases**" doesn't sound really reliable.
This is just not how it works. The way to use configurations in Play is to inject it. Please read [the docs how to access the configuration](https://www.playframework.com/documentation/2.6.x/JavaConfig#The-Typesafe-Config-API). With `ConfigFactory` you actually create a new configuration, but in a Play app the framework already created the configuration for us and the application can pass it to you (like my example).

And also, again, because you don't pass a classloader explicitly to the `load()` method, it's not guaranteed that the `load()` method is using the same classloader as which the `application.conf` is/was/will be loaded.
Why you see certain behaviour with `@Dynamic` has nothing to do with deadbolt, nor Play. I would guess this is pure coincidence (maybe other classloader is used, etc. - Play uses different classloaders at least in dev mode, but since you didn't specify who knows what will be used?). What you do is playing classloader [Roulette](https://en.wikipedia.org/wiki/Roulette).

**Comment by eximius313** [comment]
Ok, thank you for explanation
